### ISSUE TITLE
Update GfycatApiKit to use the latest AFNetworking library.

### ISSUE THREAD

**Issue by rishabdutta** [gfycat/GfycatApiKit#3]
Right now GfycatApiKit is using AFNetworking version 3.2.1 (This is from trying to install in a new project).

As we know Apple will start rejecting apps post December 2020 that has UIWebView code in it.
AFNetworking guys have removed UIWebView related stuff from their library from version 4.0.

I tried using the latest AFNetworking library and installed GfycatApiKit. Looks like some parameters have been changed in AFNetworking library that is causing GfycatApiKit library to fail.

The file is GfycatEventTracker.m in line #134.

<img width="694" alt="Screenshot 2020-05-17 at 1 45 08 AM" src="https://user-images.githubusercontent.com/14312307/82129396-16404280-97e0-11ea-9035-c7087034532d.png">

**Comment by MikaelLambert** [comment]
Thanks for using GfycatApiKit! This issue has been addressed in Pull Request #7 which was released in version 0.0.27 on GitHub and Cocoapods.
